package model.pojo;
// Generated 22/05/2017 10:06:07 PM by Hibernate Tools 4.3.1



/**
 * EscuelaId generated by hbm2java
 */
public class EscuelaId  implements java.io.Serializable {


     private int idEscuelas;
     private int nivelEducativoIdNivel;
     private int entidadIdEntidad;
     private int controlIdControl;

    public EscuelaId() {
    }

    public EscuelaId(int idEscuelas, int nivelEducativoIdNivel, int entidadIdEntidad, int controlIdControl) {
       this.idEscuelas = idEscuelas;
       this.nivelEducativoIdNivel = nivelEducativoIdNivel;
       this.entidadIdEntidad = entidadIdEntidad;
       this.controlIdControl = controlIdControl;
    }
   
    public int getIdEscuelas() {
        return this.idEscuelas;
    }
    
    public void setIdEscuelas(int idEscuelas) {
        this.idEscuelas = idEscuelas;
    }
    public int getNivelEducativoIdNivel() {
        return this.nivelEducativoIdNivel;
    }
    
    public void setNivelEducativoIdNivel(int nivelEducativoIdNivel) {
        this.nivelEducativoIdNivel = nivelEducativoIdNivel;
    }
    public int getEntidadIdEntidad() {
        return this.entidadIdEntidad;
    }
    
    public void setEntidadIdEntidad(int entidadIdEntidad) {
        this.entidadIdEntidad = entidadIdEntidad;
    }
    public int getControlIdControl() {
        return this.controlIdControl;
    }
    
    public void setControlIdControl(int controlIdControl) {
        this.controlIdControl = controlIdControl;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EscuelaId) ) return false;
		 EscuelaId castOther = ( EscuelaId ) other; 
         
		 return (this.getIdEscuelas()==castOther.getIdEscuelas())
 && (this.getNivelEducativoIdNivel()==castOther.getNivelEducativoIdNivel())
 && (this.getEntidadIdEntidad()==castOther.getEntidadIdEntidad())
 && (this.getControlIdControl()==castOther.getControlIdControl());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEscuelas();
         result = 37 * result + this.getNivelEducativoIdNivel();
         result = 37 * result + this.getEntidadIdEntidad();
         result = 37 * result + this.getControlIdControl();
         return result;
   }   


}


