package model.pojo;
// Generated 22/05/2017 10:06:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NivelEducativo generated by hbm2java
 */
public class NivelEducativo  implements java.io.Serializable {


     private Integer idNivel;
     private String nombre;
     private Set escuelas = new HashSet(0);

    public NivelEducativo() {
    }

	
    public NivelEducativo(String nombre) {
        this.nombre = nombre;
    }
    public NivelEducativo(String nombre, Set escuelas) {
       this.nombre = nombre;
       this.escuelas = escuelas;
    }
   
    public Integer getIdNivel() {
        return this.idNivel;
    }
    
    public void setIdNivel(Integer idNivel) {
        this.idNivel = idNivel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEscuelas() {
        return this.escuelas;
    }
    
    public void setEscuelas(Set escuelas) {
        this.escuelas = escuelas;
    }




}


