package model.pojo;
// Generated 22/05/2017 10:06:07 PM by Hibernate Tools 4.3.1



/**
 * PoblacionId generated by hbm2java
 */
public class PoblacionId  implements java.io.Serializable {


     private int idPoblacion;
     private int idEntidad;
     private int idRango;

    public PoblacionId() {
    }

    public PoblacionId(int idPoblacion, int idEntidad, int idRango) {
       this.idPoblacion = idPoblacion;
       this.idEntidad = idEntidad;
       this.idRango = idRango;
    }
   
    public int getIdPoblacion() {
        return this.idPoblacion;
    }
    
    public void setIdPoblacion(int idPoblacion) {
        this.idPoblacion = idPoblacion;
    }
    public int getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(int idEntidad) {
        this.idEntidad = idEntidad;
    }
    public int getIdRango() {
        return this.idRango;
    }
    
    public void setIdRango(int idRango) {
        this.idRango = idRango;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoblacionId) ) return false;
		 PoblacionId castOther = ( PoblacionId ) other; 
         
		 return (this.getIdPoblacion()==castOther.getIdPoblacion())
 && (this.getIdEntidad()==castOther.getIdEntidad())
 && (this.getIdRango()==castOther.getIdRango());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPoblacion();
         result = 37 * result + this.getIdEntidad();
         result = 37 * result + this.getIdRango();
         return result;
   }   


}


