package model.pojo;
// Generated 22/05/2017 10:06:07 PM by Hibernate Tools 4.3.1



/**
 * Poblacion generated by hbm2java
 */
public class Poblacion  implements java.io.Serializable {


     private PoblacionId id;
     private Entidad entidad;
     private RangoEdades rangoEdades;
     private long edadHombres;
     private long edadMujeres;
     private int anio;
    public Poblacion() {
    }
    
    public Poblacion(PoblacionId id, Entidad entidad, RangoEdades rangoEdades, long edadHombres, long edadMujeres, int anio) {
       this.id = id;
       this.entidad = entidad;
       this.rangoEdades = rangoEdades;
       this.edadHombres = edadHombres;
       this.edadMujeres = edadMujeres;
       this.anio = anio;
    }

    public PoblacionId getId() {
        return this.id;
    }
    
    public void setId(PoblacionId id) {
        this.id = id;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public RangoEdades getRangoEdades() {
        return this.rangoEdades;
    }
    
    public void setRangoEdades(RangoEdades rangoEdades) {
        this.rangoEdades = rangoEdades;
    }
    public long getEdadHombres() {
        return this.edadHombres;
    }
    
    public void setEdadHombres(int edadHombres) {
        this.edadHombres = edadHombres;
    }
    public long getEdadMujeres() {
        return this.edadMujeres;
    }
    
    public void setEdadMujeres(int edadMujeres) {
        this.edadMujeres = edadMujeres;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }




}


