package model.pojo;
// Generated 22/05/2017 10:06:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RangoEdades generated by hbm2java
 */
public class RangoEdades  implements java.io.Serializable {


     private Integer idRango;
     private String edades;
     private Set poblacions = new HashSet(0);

    public RangoEdades() {
    }

	
    public RangoEdades(String edades) {
        this.edades = edades;
    }
    public RangoEdades(String edades, Set poblacions) {
       this.edades = edades;
       this.poblacions = poblacions;
    }
   
    public Integer getIdRango() {
        return this.idRango;
    }
    
    public void setIdRango(Integer idRango) {
        this.idRango = idRango;
    }
    public String getEdades() {
        return this.edades;
    }
    
    public void setEdades(String edades) {
        this.edades = edades;
    }
    public Set getPoblacions() {
        return this.poblacions;
    }
    
    public void setPoblacions(Set poblacions) {
        this.poblacions = poblacions;
    }




}


