package model.pojo;
// Generated 22/05/2017 10:06:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private Integer idtipoUsuario;
     private String tipo;
     private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(String tipo) {
        this.tipo = tipo;
    }
    public TipoUsuario(String tipo, Set usuarios) {
       this.tipo = tipo;
       this.usuarios = usuarios;
    }
   
    public Integer getIdtipoUsuario() {
        return this.idtipoUsuario;
    }
    
    public void setIdtipoUsuario(Integer idtipoUsuario) {
        this.idtipoUsuario = idtipoUsuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


